# Generated by Django 2.2 on 2021-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('affiliation', models.CharField(max_length=15)),
                ('char_pic', models.CharField(max_length=50)),
                ('char_desc', models.CharField(max_length=250)),
                ('char_quotes', models.CharField(max_length=125)),
            ],
        ),
    ]
